### ISSUE TITLE
Permissions of bin directory in assembly are wrong.

### ISSUE THREAD

**Issue by rbuck** [nuodb/migration-tools#38]
Roberts-MBP:tools rbuck$ ls -al migrator
total 0
drwxr-xr-x   5 rbuck  staff  170 Jan 20 10:56 .
drwxr-xr-x   4 rbuck  staff  136 Jan 20 10:56 ..
d---------   4 rbuck  staff  136 Jan 20 10:25 bin   <<<<<<<<<<<<<<  BAD PERMS HERE
drwxr-xr-x   5 rbuck  staff  170 Jan 20 10:25 conf
drwxr-xr-x  28 rbuck  staff  952 Jan 20 10:56 jar
Roberts-MBP:tools rbuck$ ls -al migrator.orig/
total 0

**Comment by kacheri** [comment]
Merged this pull request into rel/2.1.1 
Verified that the permissions on the bin directory are as expected on the extracted nuodb-migrator.tar

[plothridge] Do you want us to merge into master ?

**Comment by mgodekere** [comment]
Merged this pull request into rel/2.1.1 
Verified that the permissions on the bin directory are as expected on the extracted nuodb-migrator.tar

[plothridge] Do you want us to merge into master ?
